---

- name: 'Install Prometheus'
  hosts: 'k3s1'
  gather_facts: true
  become: false
  module_defaults:
    kubernetes.core.helm:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s_info:
      kubeconfig: './k3s-kubeconfig'

  tasks:

    - name: 'Create the prometheus-system namespace'
      delegate_to: 'localhost'
      kubernetes.core.k8s:
        name: 'prometheus-system'
        api_version: 'v1'
        kind: 'Namespace'
        state: 'present'

    - name: 'Install prometheus via the helm chart'
      delegate_to: 'localhost'
      kubernetes.core.helm:
        chart_repo_url: 'https://prometheus-community.github.io/helm-charts'
        chart_ref: 'prometheus'
        release_name: 'prometheus'
        release_namespace: 'prometheus-system'
        release_values:
          prometheus-pushgateway:
            enabled: false
          alertmanager:
            enabled: false
        values_files: 'https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/prometheus/extraScrapeConfigs.yaml'

    - name: 'Wait until all pods are running'
      delegate_to: 'localhost'
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: prometheus-system
      register: pod_list
      until: |
        pod_list | json_query("resources[*].status.phase") | unique | sort == ["Running"]
        or
        pod_list | json_query("resources[*].status.phase") | unique | sort == ["Running", "Succeeded"]
      retries: 36
      delay: 10
